### ISSUE TITLE
[Question]: 

### ISSUE THREAD

**Issue by Sp333dyy** [AllTheMods/Spellbound#100]
### What would you like to know?

So Ive probably reched some good progress in the pack and it seems like (unless i am missing something) not many of the moded picks reach tier 6 to mine unobtanium/any ore in the other do i have to result to using tetra for that or are there any cooler endgame tool from any of the mods?

**Comment by ZephyrWindSpirit** [comment]
To my knowledge, tetra was the desired path to find a way to harvest unobtanium/Other ores.
