### ISSUE TITLE
[Crash]: Malum Rite of Growth Ticking Block Entity NPE crash

### ISSUE THREAD

**Issue by shinji257** [AllTheMods/Spellbound#101]
### Possible Fixes

Yes

### Modpack Version

other

### What happened?

ATM Spellbound 2.2.5
Possible crash from Malum Rite of Growth caused by Ticking Block Entity exception.  Resolved by replacing block out of render range with cobblestone for now.  Oddly enough the other one was just fine...

### Crash Log

https://gist.github.com/shinji257/3d8d33a48d0e14e3c15ed2a0c7dbcb06

**Comment by ZephyrWindSpirit** [comment]
Ran a few growth rites in the overworld with a variety of seeds. No crash. Closing issue
