### ISSUE TITLE
[Crash]: Evil craft/Mana and Artifice

### ISSUE THREAD

**Issue by Wolfgaing** [AllTheMods/Spellbound#102]
### Possible Fixes

Yes

### Modpack Version

other

### What happened?

updated to 2.2.6 but this was same issue in other one started working evilcraft and now every time I kill a Mana and artifice pixie 
game crashes out also cant tell if its due to the blood extractor from evil craft in inventory during kill or not

### Crash Log

https://gist.github.com/Wolfgaing/62d8c9cae369d738b8a81af3c8bec82f

**Comment by ZephyrWindSpirit** [comment]
WIth an update to both mods, this doesn't happen, with having a blood extractor. Can close now.
