### ISSUE TITLE
[Question]: Quest book question quest

### ISSUE THREAD

**Issue by Jean3000** [AllTheMods/Spellbound#103]
### What would you like to know?

Say that ten times fast.

Are the quest in the quest book that are just questions a coming soon kind of thing or just suggestions?

**Comment by ZephyrWindSpirit** [comment]
The wip quests (which I wrote) were unfinished with an uncertain fate. Some may become just info quests. Others will disappear, or get finished.

**Comment by ZephyrWindSpirit** [comment]
Cleaned up the questbook and completed or removed wip quests.
