### ISSUE TITLE
Create's Crushed Aluminum has no usage / missing recipe

### ISSUE THREAD

**Issue by Krymms** [AllTheMods/Spellbound#105]
### Possible Fixes

Yes

### Modpack Version

other

### What happened?

Crushing aluminum ore with Create's machines results in unusable crushed aluminum which can not be further processed

Same applies to: uranium, osmium and nickel

### latest.log

.

**Comment by MadWomen** [comment]
how do you even get osmium, uranium and nickel? they are supposed to be disabled.

**Comment by Krymms** [comment]
The 3 are disabled, but aluminum isn't. I was just stating which of the crushed ores are missing recipes.

**Comment by MadWomen** [comment]
i can look at the aluminum for sure.

**Comment by ZephyrWindSpirit** [comment]
Aluminum, tin and other non-magic mod ores are being removed. so this issue will be solved.
