### ISSUE TITLE
Runs extremely poorly

### ISSUE THREAD

**Issue by AtlasThe1st** [AllTheMods/Spellbound#108]
Pack doesn't go over 2 FPS, my pc isn't very good, but I have no problem running other packs, it wouldn't be so bad if I could add Optifine, but one or more mods in the pack cause a crash when Optifine is added. I had high hopes for this pack as it has many mods I like, but it's literally unplayable

**Comment by MishievousCloud** [comment]
Im having the same issues with a top of the line GPU and CPU, so its very much so the pack.

**Comment by BlueStriker101** [comment]
Same issues. The devs need to address this or at least provide some form of input. Support for spellbound seems mostly nonexistent now

**Comment by ZephyrWindSpirit** [comment]
Mipmaps seem to be causing issues, but turning off mipmaps seem to make the pack run smoother. Also tinker with your graphics settings.
