### ISSUE TITLE
[Crash]: Evilcraft (evilcraft) encountered an error during the load_registries event phase

### ISSUE THREAD

**Issue by rtx2090ti** [AllTheMods/Spellbound#110]
### Possible Fixes

Yes

### Modpack Version

other

### What happened?

I downloaded the modpack (Version "Spellbound-2.2.7.zip") through the Curseforge app, and then downloaded Forge 1.16.5 (Version "36.2.31") and as soon as the Forge loading screen finished I was met with an error screen

### Crash Log

https://gist.github.com/rtx2090ti/9641d75716a6cae67fbda05840fbae56

**Comment by ZephyrWindSpirit** [comment]
Updating evilcraft and cyclopscore, I haven't seen this error. Closing.
