### ISSUE TITLE
[Crash]: create: Engineer's Goggles crash the game

### ISSUE THREAD

**Issue by gatoloko32** [AllTheMods/Spellbound#111]
### Possible Fixes

No

### Modpack Version

other

### What happened?

Tried crafting [Engineer's Goggles} from create, and when it appeared as a result of the craft, game instantly froze and crashed.
Also noticed it on JEI sais : "Tooltip Error, see log" when hovering over the goggles

i'm playing on 2.2.6, and i know 2.2.7 came out like 1 or 2 days ago.

### Crash Log

https://gist.github.com/gatoloko32/3be76806d34d28d8c152fde9ff766cbb

**Comment by ZephyrWindSpirit** [comment]
Updating create, I don't get this crash. Solved by update.
