### ISSUE TITLE
[Crash][2.2.7]: Crash on world startup after "Loading terrain"

### ISSUE THREAD

**Issue by JunoMeow** [AllTheMods/Spellbound#115]
### Possible Fixes

Yes

### Modpack Version

other

### What happened?

After few days of continuous playing, the game stopped loading the world and it crashes on startup
Been playing with optifine, after it started crashing i removed optifine and tried to load it few more times, but the result is the same. Also tried to update mods and to give more ram memory, the problem still consists.

Version of modpack: 2.2.7 (latest), started playing few days ago.  Of course i can rollback to a backup to see if it fixes the problem with loading, but I'm not sure if it is a right way to solve the problem.

### Crash Log

https://gist.github.com/JunoMeow/afaa07120987f007f519a496216c3ecc

**Comment by ZephyrWindSpirit** [comment]
Update.
