### ISSUE TITLE
[Question]: 

### ISSUE THREAD

**Issue by hinauri** [AllTheMods/Spellbound#116]
### What would you like to know?

I have a big question my game when I run the mod pack for the first time everything is fine but when I create a world I close the mod pack and when I relaunch the mode pack my game tells me there is a problem as indicated below is that you could help me or not to solve this problem because I would like to play with the mod pack
![IMG_20220402_174542](https://user-images.githubusercontent.com/102911680/161432442-7b8ce3c0-b834-476c-9279-7bb5658c2c59.jpg)

**Comment by Mitchell5200** [comment]
As per the error message, PC Driver issue, Update your drivers
