### ISSUE TITLE
[Bug]: Invincibility bug

### ISSUE THREAD

**Issue by PVPM** [AllTheMods/Spellbound#117]
### Possible Fixes

Yes

### Modpack Version

2.1.4

### What happened?

One day i noticed that i cant lose any hearts. Tried using /kill, swimming in lava, poison, wuther drowning and nothing worked. Only expection is that i still get blood magic dmg but it cant be lethal - if i have 1 hp left, self-sacrifice wont kill me but altar will be still filled with blood. Im a werewolf lvl 7 if that changes anything. 

### latest.log

https://gist.github.com/PVPM/a96c8a981d90d82bc1727b7df309b075

**Comment by The13thEmpire** [comment]
I have the same issue, same version
Dedicated Server

I am werewolf-lord level 4
Attuned to Amara(Armor) in Astral Sorcery 
Some times the life-mending enchantment does damage but it is inconsistent.

Using /kill still triggers Totem of Undying but not Phoenix Blessing perk from Astral Sorcery.

**Comment by The13thEmpire** [comment]
I did some more testing. It seems to happen when you put on the Ring of Seven Curses and it persists even after you take it off.

**Comment by Jax1366** [comment]
after multiple attempts all the times this glitch occurred it revolved somewhere in time around werewolf, ring of seven curses, and armor value going above a certain number

**Comment by ZephyrWindSpirit** [comment]
Need to investigate this.

**Comment by ZephyrWindSpirit** [comment]
I want you boys to crosspost this bug with astral sorcery and werewolves' githubs to see if its an interaction between those two mods. Nothing we can do on this one. Congrats on immortality.
