### ISSUE TITLE
Extremely bad perfomance 

### ISSUE THREAD

**Issue by emredurak01** [AllTheMods/Spellbound#118]
The pack runs extremely poorly. Initially, it was a constant 1 fps but after disabling Mipmap it somehow got around ~20 fps but it's still really bad. Optifine and Magnesium give crash.

RX 6600, Ryzen 5 2600

**Comment by BlueStriker101** [comment]
Same issue here. Honestly disappointing that you haven't gotten a response from the devs. Even jn their discord there's basically no support for Spellbound

**Comment by emredurak01** [comment]
Yep, it's a shame. I really wanted to try it.

**Comment by ZephyrWindSpirit** [comment]
10-30 frames is my normal play amount and I'm on an old computer. Tinker with your graphics settings and particles and it runs smoother.
