### ISSUE TITLE
[Crash]: Crash on startup

### ISSUE THREAD

**Issue by QuinnActually** [AllTheMods/Spellbound#120]
### Possible Fixes

Yes

### Modpack Version

other

### What happened?

Whenever I attempt to launch the game, it loads for about 5-10 seconds before immediately crashing. No modifications have been made to the files, and I even made a second installation to make sure nothing external was screwing with anything. I've attached latest.log and debug.log—Forge didn't even load for long enough to generate a crash report of its own.

### Crash Log

https://gist.github.com/QuinnActually/22d5f48046a0da535ceed87b1af55b80

**Comment by QuinnActually** [comment]
I HAVE DISCOVERED THE ISSUE: Apparently Minecraft 1.18 auto-installs JDK 18 when first running, and Forge 1.16 is currently incompatible with JDK 18. Uninstalling and reverting to an older version of Java fixed the issue!

**Comment by GoldyFoxie** [comment]
> I HAVE DISCOVERED THE ISSUE: Apparently Minecraft 1.18 auto-installs JDK 18 when first running, and Forge 1.16 is currently incompatible with JDK 18. Uninstalling JDK 18 and reverting to an older version of Java fixed the issue!

but how can we uninstall it ?

**Comment by Edua2007** [comment]
I uninstalled it and it still doesn't work
