### ISSUE TITLE
[Bug]: Connected textures not working

### ISSUE THREAD

**Issue by gaguilar27** [AllTheMods/Spellbound#121]
### Possible Fixes

Yes

### Modpack Version

other

### What happened?

I want to see the texture of the glass connected, but the mod is not working. Anyone with the same problem?

### latest.log

https://gist.github.com/gaguilar27/a5a1fa97d7f3b7eb7f5ecb2783547894

**Comment by Mitchell5200** [comment]
Vanilla glass does not have connected textures in this pack, and the Log link is expired/invalid. Closing
