### ISSUE TITLE
[Question]: Why the constructs of Mana and artifice won't plant mystical agriculture seeds ?

### ISSUE THREAD

**Issue by Hether568** [AllTheMods/Spellbound#122]
### What would you like to know?

I've trying to automate inferium farm but it appears the constructs from mana and artifice said "I WON'T PLANT THIS"

Is there a way to make this possible ?

I love his modpack and i'm having a lot of fun playing it!

Thank you for your time !

**Comment by ZephyrWindSpirit** [comment]
Try this again with an update. Sounds like Mana and artifice is working actively on compatibility.
https://github.com/Mithion/Mana-And-Artifice/issues/305
