### ISSUE TITLE
[Crash]: Exit code 255

### ISSUE THREAD

**Issue by ForSakenAngel222** [AllTheMods/Spellbound#124]
### Possible Fixes

Yes

### Modpack Version

2.1.4

### What happened?

<img width="664" alt="Screen Shot 2022-04-18 at 3 33 24 PM" src="https://user-images.githubusercontent.com/103963163/163869180-4841e77f-44be-4993-aed2-c08279ac64d2.png">

### Crash Log

https://gist.github.com/ForSakenAngel222/17d74da1b75fd41337a42339fd908d97

**Comment by ZephyrWindSpirit** [comment]
Old crash.
