### ISSUE TITLE
[Question]: is development of ATMS still continues?

### ISSUE THREAD

**Issue by JunoMeow** [AllTheMods/Spellbound#125]
### What would you like to know?

I see many new issues (plus mine, which i've opened more than two weeks ago) and almost no answers or possible solutions on them by modmakers.

**Comment by Mitchell5200** [comment]
Yes the pack is still receiving updates. The main pack developer for spellbound has had some IRL issues for some time, we (the rest of the ATM team) are working on a update to hopefully be released before christmas 2022
