### ISSUE TITLE
Is Infinite Netherite Intended?

### ISSUE THREAD

**Issue by Root4222** [AllTheMods/Spellbound#127]
If you take netherite scraps, put them into the Alchemichal reaction chamber (Blood Magic) you get an Item you can put into the runeforge (Mana and Artifice) with the item doubeling upgrade you get 2 Netherite scraps and you can repeat the process. It doesn't work with gold, so I thought it might not be Intended.

**Comment by ZephyrWindSpirit** [comment]
Will investigate
