### ISSUE TITLE
Constant crashing with malum mod

### ISSUE THREAD

**Issue by FieryForest** [AllTheMods/Spellbound#129]
### Possible Fixes

No

### Modpack Version

other

### What happened?

every time i try to craft the "radiant soulstone" from the mod "malum" using the "spirit alter" my game crashes and it wont allow be to go back into the game. The only fix ive found is just to load up a backup. I've repeated this three times just to make sure its not a one time thing, it happens every time. Im on version 2.2.7 of the modpack.

### Crash Log

<script src="https://gist.github.com/FieryForest/24075435f864ca27790e663317dce55b.js"></script>

**Comment by InfiniteMalice** [comment]
Hmmm... "Ticking block entity" To get around this I moved my spirit altar. Even picked it up and placed it down again. For me, that seemed to work.

**Comment by ZephyrWindSpirit** [comment]
Tested that and I didn't crash, both ways. Wonder if it was an interaction with something else.
