### ISSUE TITLE
Crash:java.lang.ArrayIndexOutOfBoundsException: 111

### ISSUE THREAD

**Issue by Tybomb12** [AllTheMods/Spellbound#130]
### Possible Fixes

Yes

### Modpack Version

other

### What happened?

Every single time i try to make a single world it crashes.  Can't even play the mod at all

### Crash Log

https://gist.github.com/Tybomb12/b886961e99920d9c9cc68b0b6946e598

**Comment by ZephyrWindSpirit** [comment]
Iron furnaces rendering crash. update.
