### ISSUE TITLE
I get random effects when hitting

### ISSUE THREAD

**Issue by DarKXK** [AllTheMods/Spellbound#133]
I know there is an enchantment that does this, but what i mean is that i get it even using my punch, it all started when i exited everbright and i don't know what's happening, everything before that was normal.

**Comment by ZephyrWindSpirit** [comment]
Its a certain enchantment called gloom. If whatever you're hitting has it on their armor, you get negative effects. If YOU have blessing on your armor, it gives you a random POSITIVE effect.
