### ISSUE TITLE
[Crash]: 

### ISSUE THREAD

**Issue by ariel1397** [AllTheMods/Spellbound#134]
### Possible Fixes

Yes

### Modpack Version

other

### What happened?

My friends and I started a server with the “all the magic spellbound “ mod pack every 2-3 minutes I get that disconnected error(also I’m the only one getting this error ) . every 2-3 times i get disconected when icome back to the game and its getting so laggy that its not possible to play so i need to restart the all game
![IMG_7504](https://user-images.githubusercontent.com/111662479/185766087-c9256170-d86b-4d85-9d71-87483a31a266.jpg)
![IMG_7505](https://user-images.githubusercontent.com/111662479/185766094-026a179e-3483-4107-a2b9-a60b71d878c7.jpg)
 

### Crash Log

https://gist.github.com/arie1397

**Comment by ZephyrWindSpirit** [comment]
crashlog link broken. Closed. Update.
