### ISSUE TITLE
[Feature]: Problems caused by gold backpacks

### ISSUE THREAD

**Issue by qiyu666** [AllTheMods/Spellbound#135]
### Feature Details

![image](https://user-images.githubusercontent.com/79317749/189514381-ebec6ad5-d8dd-4f92-8412-4f5dcb46bed8.png)
我打开金质背包之后的页面，上下面超过了屏幕，从这个等级往上都有这个问题

When I open the gold backpack, the backpack ui will cause the upper and lower parts to be blocked. Backpacks from this level will have this problem

**Comment by KamiAso** [comment]
Do you expect someone will understand?

**Comment by InfiniteMalice** [comment]
Are you in full window mode? I have an easier time with it in full window mode than in windowed mode.

**Comment by Mitchell5200** [comment]
Gui scale and Window size issue, Closing
