### ISSUE TITLE
Evilcraft 144,000 mB Tank turned into a 16,000 mB tank

### ISSUE THREAD

**Issue by JWAOSTAR** [AllTheMods/Spellbound#136]
I crafted a 144,000 mB Tank so I didn't have to keeping going back to my house to store blood but when I put it down and broke it, the tank became a 16,000 mB tank.

**Comment by JWAOSTAR** [comment]
Also just a side thing that might actually be connected every time I brake the tank I lose the blood. I am not sure if that is by design but may explain, because that would mean that the drop is the wrong item.

**Comment by InfiniteMalice** [comment]
Is this the case when you use silktouch?

**Comment by ZephyrWindSpirit** [comment]
Updating the mod appears to have solved this issue. I've broken several tanks and have no wrong items breaking.
