### ISSUE TITLE
[Crash]:  Entering Either Blue Skies Dimensions

### ISSUE THREAD

**Issue by Tooth52less** [AllTheMods/Spellbound#137]
### Possible Fixes

Yes

### Modpack Version

other

### What happened?

Every time I enter either blue skies dimension, loads in fine but after ~5 seconds the game freezes and crashes on version 2.2.7 (doesn't seem to be in the drop down list for modpack version)
Have tried:
Increasing ram, results in massive lag when generating new chunks
Uninstalling and reinstalling the pack
Restarting computer
Lowering render distance to lowest

Additional crashes also happen when I die within the end dimension, and when I kill the ender dragon, but those arn't as annoying as being gated from a mod.

### Crash Log

<script src="https://gist.github.com/Tooth52less/a87d49bc2f818a8e6d712dc290b9486e.js"></script>

**Comment by InfiniteMalice** [comment]
Try increasing the memory used. Click on the mod in Cursed Forge, you should see three-dot options. Now go to profile options. You should be able to increase memory.

**Comment by Mitchell5200** [comment]
I'm Unable to re-create this crash on my PC, if increasing RAM and updating drivers ect. does not fix this for you, i do not have any other fixes, as the mod also does not have any other 1.16 versions.

Closing anyway.
