### ISSUE TITLE
[Crash]: Pose stack not empty

### ISSUE THREAD

**Issue by InfiniteMalice** [AllTheMods/Spellbound#138]
### Possible Fixes

Yes

### Modpack Version

other

### What happened?

Spellbound 2.2.7

The first time the crash occurred was when I created a Runic Tenebris Core from Forbidden and Arcanus. 
The second time was after creating the Turtlemancy wand. 

I have already restored it from a backup once. The log file indicates Twilight Forest for being the problem in both cases. Not sure why that is.

### Crash Log

https://gist.github.com/InfiniteMalice/ae55ed36a425510cb5952d0935ecab65

**Comment by ZephyrWindSpirit** [comment]
Update your drivers, looks like a hardware error.
