### ISSUE TITLE
[Question]: disable the minimap (+ less cluttered UI)?

### ISSUE THREAD

**Issue by KateHanami** [AllTheMods/Spellbound#142]
### What would you like to know?

long story short, I play on a tiny screen (not a lie) and I need the UI to be as clean as possible, 
inventory and stuff is ok but I need to sanitize the in-game UI as much as possible, only having the hotbar if I can

what hotkeys / menus I need to click to disable all that clutter? or do I have to remove some mods off the instance? if so, which ones? or maybe some ini settings?

**Comment by ZephyrWindSpirit** [comment]
If the mahou tsukai mana amount is bothering you, it can be configured in a different space using the client config. Usually, it doesn't show UNLESS you start the mod, so it should have a keybind to hide it. The map can be disabled in-game settings, similar to mana and artifice. Ars Nouveau's mana bar only shows when holding the spellbook for casting. One probe can be configured by the sheet of paper in the akashic tome granted on the first join.

**Comment by ZephyrWindSpirit** [comment]
Updated mahou tsukai UI to not overlap, the rest depends on the player.
