### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by Remains808** [AllTheMods/Spellbound#147]
### Possible Fixes

Yes

### Modpack Version

other

### What happened?

current version: 2.2.7
Public server
the Evil Craft werewolfs do not drop Werewolf Flesh. an item needed to craft the ATM star.   the other option is Humanoid flesh, however it is a small chance to drop when the player dies and for members wearing the cursed ring would be game ending to collect several peices to craft the stars needed to make the creative items.
I have tried killed hundred of Evil Craft werewolfs both transformed and in villager form.   and my current sword has Looting 166 and Scavenger 161. if it could drop i would have gotten one.  
![sword enchants](https://user-images.githubusercontent.com/117918447/201106815-f24e1240-2274-454f-8e6e-897f971b44e8.png)

### latest.log

none

**Comment by ZephyrWindSpirit** [comment]
With a fresh updated install and configs of Evilcraft 1.1.17 (release rn has 1.1.16, which does have a reported bug about this), by killing evilcraft werewolves at the full moon with a very heavily enchanted looting sword, I can confirm the werewolf flesh does drop. 
In the meantime, a player should save their humanoid flesh if possible.
