### ISSUE TITLE
[Crash]: Ticking Entity Champions bullet?

### ISSUE THREAD

**Issue by ZephyrWindSpirit** [AllTheMods/Spellbound#162]
### Possible Fixes

No

### Modpack Version

other

### What happened?

Clicked on a lingering mana potion in jei, briefly froze up, then crashed. 

Extra mods: Cyber's better animal models, fullbrightnesstoggle

### Crash Log

https://gist.github.com/ZephyrWindSpirit/9678a52b0474ad4e94fd3527235c5667

**Comment by ZephyrWindSpirit** [comment]
According to the crashlog, it appears that helping herds crashes on striking any entity with a projectile. 
Helping herds will be pulled when another update is performed.

**Comment by TigerWalts** [comment]
I have reported this bug to Helping Herds: https://github.com/beeshroom/HelpingHerds/issues/3
