### ISSUE TITLE
Spellbound Mod Suggestions

### ISSUE THREAD

**Issue by Pdiddy973** [AllTheMods/Spellbound#2]
Here is a new place to share mods you would like to see in  Spellbound
**Make sure they are updated to 1.16.5 before asking!**

If your post is deleted it was just reviewed and either added or decided against for now.
One submission per post to make it easier. If you want a mod, make sure it wasn't already posted.

The post should have the mod's name and the link to CurseForge's website.
Any posts not respecting the rules will be deleted.

**Comment by LadyGrelka** [comment]
JourneyMap  https://www.curseforge.com/minecraft/mc-mods/journeymap

**Comment by LadyGrelka** [comment]
Pam's HarvestCraft 2 Food Core  https://www.curseforge.com/minecraft/mc-mods/pams-harvestcraft-2-food-core

**Comment by LadyGrelka** [comment]
Pam's HarvestCraft 2 - Food Extended https://www.curseforge.com/minecraft/mc-mods/pams-harvestcraft-2-food-extended

**Comment by LadyGrelka** [comment]
Pam's HarvestCraft 2 - Crops https://www.curseforge.com/minecraft/mc-mods/pams-harvestcraft-2-crops

**Comment by LadyGrelka** [comment]
Pam's HarvestCraft 2 - Trees https://www.curseforge.com/minecraft/mc-mods/pams-harvestcraft-2-trees

**Comment by LadyGrelka** [comment]
Cooking for Blockheads https://www.curseforge.com/minecraft/mc-mods/cooking-for-blockheads/files

**Comment by LadyGrelka** [comment]
Farming for Blockheads https://www.curseforge.com/minecraft/mc-mods/farming-for-blockheads/files

**Comment by Grath** [comment]
Trample Stopper: https://www.curseforge.com/minecraft/mc-mods/trample-stopper/files

**Comment by TheOne1201** [comment]
Eidolons Hexblades: https://www.curseforge.com/minecraft/mc-mods/eidolons-hexblades

**Comment by TheOne1201** [comment]
tarot https://www.curseforge.com/minecraft/mc-mods/tarot

**Comment by TupacTheLazy** [comment]
Convenient curios container https://www.curseforge.com/minecraft/mc-mods/convenient-curios-container

**Comment by TheOne1201** [comment]
twilight decor https://www.curseforge.com/minecraft/mc-mods/twilightdecor

**Comment by TheOne1201** [comment]
JEED https://www.curseforge.com/minecraft/mc-mods/just-enough-effect-descriptions-jeed

**Comment by shBLOCK** [comment]
Incorporeal 2 https://www.curseforge.com/minecraft/mc-mods/incorporeal-2-rhododendrite

**Comment by Kevin-Marsh** [comment]
Create: Crafts and Additions [https://www.curseforge.com/minecraft/mc-mods/createaddition](url)

**Comment by Kevin-Marsh** [comment]
Pedestals [https://www.curseforge.com/minecraft/mc-mods/pedestals](url)
There are a few mods in the game such as Resourceful bees and Iron furnaces that could benefit from having a source of RF generation. These two mods would fit in nicely while providing rf and not taking away from the direction of the pack.

**Comment by shBLOCK** [comment]
Two Psi addons:
Phi https://www.curseforge.com/minecraft/mc-mods/phi
Psionic Peripherals https://www.curseforge.com/minecraft/mc-mods/psionic-peripherals

**Comment by Rawrling** [comment]
Redstone Pen  https://www.curseforge.com/minecraft/mc-mods/redstone-pen

**Comment by ZephyrWindSpirit** [comment]
> Redstone Pen https://www.curseforge.com/minecraft/mc-mods/redstone-pen

That's already in

**Comment by KirinDave** [comment]
Please consider Various Oddities and Various Equipment. VE adds a bunch of simple low-end magical and non-magical tools (e.g., a hood to hide your nameplate, chairs, and streamer tools like green screens and soon they'll have tracking dots for special effects compositing, not unlike how real life special effects motion track objects).

Various Oddities adds a scriptable and comprehensive racial system, including some extremely hard mode tools that interact correctly with things like GameStages. Examples of possible races (some included by default):

- A automaton with more health that does not heal without magic.
- A terraria style flight mechanism for bird people that is not creative (with multiple levels)
- An undead that can only heal by evil magic and weak to holy damage, that doesn't breathe or eat.
- A dwarf, tiny but naturally mines faster.
- A fae, strong against most damage but critically weak against silver weapons.
- A merfolk that has reverse drowning rules and superior underwater capabilities.

You can literally build them mix and match, let quests or server gates redefine quests, and you can even tie patron/staff names to races so they automatically get a harder or easier time of your modpack.

And I volunteer to help write the race files, if you need someone to give you a starting point.

**Comment by Ahrkonh** [comment]
I would love to see 
allomancy https://www.curseforge.com/minecraft/mc-mods/allomancy 
and 
feruchemy https://www.curseforge.com/minecraft/mc-mods/feruchemy-allomancy
Added in please

**Comment by strangeoddity** [comment]
I'd second Mahou Tsukai, though possibly with the explosive wand nerfed!

**Comment by ClockwiseGear** [comment]
Potion ID Packet Fixer https://www.curseforge.com/minecraft/mc-mods/potion-id-packet-fixer
as suggested in Issue #75. This would fix Mahou Tsukai's Bleeding effect being overwritten with Blindness.

**Comment by ClockwiseGear** [comment]
Minecolonies https://www.curseforge.com/minecraft/mc-mods/minecolonies would be super cool, especially if there was some way to tie progression into managing your settlement. Building up your own mage city would be super cool.

**Comment by davethwave** [comment]
Minecolonies aren't the best idea, especially server wise. Would be one of the leading cause of tps issues in that regard sadly.

**Comment by Timelife** [comment]
Not a mod, but a datapack to make End cities MUCH more interesting. I recalled playing with this ion Enigmatica 6 and was blown away. The version that uses Better End - Forge is even better looking.

https://www.planetminecraft.com/data-pack/end-city-for-better-end-forge-port/

Also, FYI, chests in End cities and ships are not converting to Lootr chests for some reason. I have put a post in the issues.

**Comment by strangeoddity** [comment]
Just cos it's cute, Doggy Talents: https://www.curseforge.com/minecraft/mc-mods/doggy-talents

**Comment by shBLOCK** [comment]
Interactive Corporea: https://www.curseforge.com/minecraft/mc-mods/interactive-corporea

**Comment by Llenzzz** [comment]
Extra Botany
https://www.curseforge.com/minecraft/mc-mods/extrabotany

Adds another layer of challenge with Gaia III, a significantly stronger opponent that prevents you from using non botania or non vanilla armors during the fight and deals high amounts of damage rewarding you with more, powerful relics. Additional Functional and Generating Flowers plus 4 New Armor Sets and tons of new weaponry are available for players to choose from.

**Comment by Llenzzz** [comment]
Bumping: Eidolon's Hexblades
https://www.curseforge.com/minecraft/mc-mods/eidolons-hexblades

To further expand on Eidolon weaponry, allow for Botania integration on Petal Apothecary automatic refills, and waive the need for a flint and steel to start rituals by casting the Holy Sign three times.

**Comment by shBLOCK** [comment]
Tiny Redstone:
https://www.curseforge.com/minecraft/mc-mods/tiny-redstone

**Comment by Andargus** [comment]
Zettai Ars:  A mod that combines Mana & Artifice with Ars Nouveau. 
https://www.curseforge.com/minecraft/mc-mods/zettai-ars

**Comment by SirEdvin** [comment]
Maybe i can suggest cobblestone gen tweaks https://www.curseforge.com/minecraft/mc-mods/cobblegenrandomizer

**Comment by MuchOcean** [comment]
Should add Minecolonies to build a magic themed village https://www.curseforge.com/minecraft/mc-mods/minecolonies/files

**Comment by ZephyrWindSpirit** [comment]
Mods are picked and choices are now closed. Thank you for your suggestions.
