### ISSUE TITLE
[Bug]: Materials for Stoned Bee to breed unavailable 

### ISSUE THREAD

**Issue by Boredage** [AllTheMods/Spellbound#21]
### Possible Fixes

Yes

### Modpack Version

2.1.4

### What happened?

Material for breed stoned bee unavailable due to immersive engineering not in the pack 

Configs say industrial hemp.

I suggest you use tall mystical green flowers or something similar.

### latest.log

None

**Comment by MadWomen** [comment]
fixed in the next version!
