### ISSUE TITLE
[Bug]: can't join in server

### ISSUE THREAD

**Issue by xiaoACE6716** [AllTheMods/Spellbound#25]
### Possible Fixes

Yes

### Modpack Version

2.1.4

### What happened?

![test01](https://user-images.githubusercontent.com/94223505/141620415-d2a020af-a746-4f8a-b5f3-a7564c6c90fe.png)

### latest.log

https://gist.github.com/xiaoACE6716/9c8e2521677404b5d8b4ac4732858dac

**Comment by MadWomen** [comment]
reinstall the game and server, this error happens sometimes with packs.
