### ISSUE TITLE
Wandering Trader Recipe Suggestion

### ISSUE THREAD

**Issue by Mg138** [AllTheMods/Spellbound#27]
Please, it's too hard to get, I've been afking for the whole day and not a single one has spawned, please add some other way to obtain wandering trader.

---

I think it's perfectly okay to add if it's bottlenecking progression with boredom and nothing to do. The recipe can be extremely expensive, but at least it's more approachable than waiting all day.

**Comment by ZephyrWindSpirit** [comment]
Will look into a birthing altar recipe or similar for spawning a wandering trader; I haven't done enough afk to find out whether this remains true as this is a very old issue now.

**Comment by ZephyrWindSpirit** [comment]
Wandering trader and his llamas are summonable by natures aura now.
