### ISSUE TITLE
[Bug]: eternal encryption on trying to join server

### ISSUE THREAD

**Issue by davethwave** [AllTheMods/Spellbound#29]
### Possible Fixes

Yes

### Modpack Version

other

### What happened?

About half the time it when I attempt to join a server I get stuck on the encryption part of joining a server for some unknown reason and when I try to cancel the join the game crashes causing me to have to reload the game again. The bug persisted through all the versions that I've played so far. I believe that the issue might have been caused partially due to hardware since I'm running a pretty powerful machine from almost a decade ago. From what I can tell from the logs there is a chance that the problem could be related to the resourceful bees mod but I'm not sure 100% that's it. I also haven't seen anyone else suffer from this so if anything it's not a huge deal if it can't be fixed.

### latest.log

https://gist.github.com/davethwave/9ab233ded1f58c1ba155d7b938d71eb5

**Comment by davethwave** [comment]
also the modpack version is 2.1.6 but since github hasn't been updated to reflect that I set it as other.

**Comment by ZephyrWindSpirit** [comment]
Since this is a very old issue, and the log doesn't seem to point anything out specifically, going to close this issue. 
Try out 2.2.7 and see if you get the same issue please.
