### ISSUE TITLE
[Bug]: Upgrade causes settings to reset 

### ISSUE THREAD

**Issue by Zirnike** [AllTheMods/Spellbound#32]
### Possible Fixes

Yes

### Modpack Version

2.1.4

### What happened?

When I upgrade to a new version, HUD settings for Mana and Artifice, mouse invert, fullscreen, subtitles, and keyboard controls reset to default.  I tested on another modpack in Curseforge, and this does not happen.  All 3 times I have updated this has occurred.  

### latest.log

https://gist.github.com/Zirnike/feabd64b8dd280001730a9cf6a59744f

**Comment by MadWomen** [comment]
we do ship the pack with a few standard setting, you can save the options.txt and put it back after the upgrade to retain your settings.
