### ISSUE TITLE
[Bug]: Zinc nuggets unobtainable

### ISSUE THREAD

**Issue by ReflectionGolden** [AllTheMods/Spellbound#33]
### Possible Fixes

Yes

### Modpack Version

2.1.4

### What happened?

The recipes which should give zinc nuggets either don't exist (in terms of crafting to do so) or cause all materials to just disappear (as with washing crushed zinc ore).

### latest.log

https://gist.github.com/ReflectionGolden/6a22a24c51860714dddaa691b34aa501

**Comment by MadWomen** [comment]
since tin isn't used in the pack, adding the tin bee to breed would be pointles, instead i've set the zinc bee to naturally spawn in the world, no need to breed up to it anymore for that bee.

**Comment by eseven77** [comment]
Tin is used to craft pewter isn't it? I am not being able to find the ore...
