### ISSUE TITLE
Server Starter 2.0.1 [Bug]: Maximum heap size error

### ISSUE THREAD

**Issue by sebstjean2001** [AllTheMods/Spellbound#37]
### Possible Fixes

Yes

### Modpack Version

other

### What happened?

When I run the serverstarter-2.0.1 with a max ram of 4G or more in the server-setup-config, it says invalid max heap. But if I put my max ram to anything under 4G, I get error that I cannot reserve enough space for object heap. Also my laptop has 16G of ram if this info has any value. 

I'm just trying to setting a server for me and my friends. I don't know if I'm missing something or its a actual bug.

![image](https://user-images.githubusercontent.com/94570696/142286914-09185755-2e79-4218-8f63-e69ea17a9d5e.png)

![image](https://user-images.githubusercontent.com/94570696/142285899-f23d9ed4-0eaa-45a7-a34b-4502d438af31.png)

![image](https://user-images.githubusercontent.com/94570696/142286123-537a983d-df16-49d0-aa2d-ca750a5b8e06.png)

### latest.log

there isnt one for the server folder

**Comment by Tanyrus** [comment]
How much RAM is your laptop using before you attempt to start the Server?

**Comment by MadWomen** [comment]
sounds like the classic 32bit os problem, so check that first, if you have a 32bit os, you cannot allocate more than 3gb of ram no matter what you do.

you have to install a 64 bit OS to be able to use more than 3gb of ram.
