### ISSUE TITLE
[Feature]: Unable to Craft Eidolon's Mind-Shielding Plate with AllTheOres Lead Ingots

### ISSUE THREAD

**Issue by KJ40000** [AllTheMods/Spellbound#38]
### Feature Details

Unable to craft the Mind-Shielding plate from Eidolon without the ingots from said mod
![2021-11-18_22 41 37](https://user-images.githubusercontent.com/6509236/142561320-53fca5bd-4a64-4c0e-b21c-8d2f7f52e23c.png)
![2021-11-18_22 41 30](https://user-images.githubusercontent.com/6509236/142561323-6d6bea62-2040-4088-bbc3-0b7e75b274a9.png)
.

**Comment by ZephyrWindSpirit** [comment]
fixed for future release.
