### ISSUE TITLE
[Bug]: Evil Craft Brooms not craftable

### ISSUE THREAD

**Issue by Siegurd33** [AllTheMods/Spellbound#40]
### Possible Fixes

Yes

### Modpack Version

other

### What happened?

Version 2.1.8

EvilCraft flying brooms do not have a recipe. The broom parts do not have a recipe. If you try to use the recipe from the EvilCraft manual, an invisible "Broom Part" item is craftable. These invisible items will consume materials as if you were giving them a material type, but they remain unable to be combined into a full broom.

If you give yourself the broom using creative mode, it has no stats (Speed, Acceleration, etc.) and won't fly
<img width="606" alt="Broom" src="https://user-images.githubusercontent.com/94941390/143153068-60f09610-335f-49c5-a2d3-cb9b8fd10543.png">
.

### latest.log

https://aka.ms/snapshotbugs?ref=game

**Comment by Mitchell5200** [comment]
Confirmed fixed in V2.2.7, Closing
