### ISSUE TITLE
Enigmatic Amulet not receive when you create a new world.

### ISSUE THREAD

**Issue by Apersoma** [AllTheMods/Spellbound#41]
When you make a new world you're supposed to get the enigmatic amulet if you have the enigmatic legacy mod, but you don't. If it's a balance thing, I'd at least add a way to obtain it.

**Comment by ZephyrWindSpirit** [comment]
I'm doing some testing of reenabling the enigmatic amulet but it would require DISABLING corail tombstones player gravestones to work properly with the ring of seven curses.
I do not know how the resulting item that comes from dying with the enigmatic amulet equipped reacts if you die and there is no place to spawn the entity, or in a protected ftbchunks claim. If you die in another player's area, are you stuck retrieving your things?
All things we need to examine before saying a 'yes, we can reenable/set a crafting recipe for it' or 'no'. 

Not to mention enigmatic legacy doesn't seem to recognize curios slots when equipping your gear after getting it back from this entity.

**Comment by ZephyrWindSpirit** [comment]
For now, its gonna remain disabled.
If you want it for yourself, go in the enigmaticlegacy config and switch enigmatic amulet to TRUE.
