### ISSUE TITLE
[Crash]: Exception in thread "ResearchIOThread" Exception in thread "WorldCacheIOThread>

### ISSUE THREAD

**Issue by SquTM** [AllTheMods/Spellbound#42]
### Possible Fixes

No

### Modpack Version

2.1.4

### What happened?

I host the server for my community and the server keeps randomly crashing on this any ideas thanks.? 

### Crash Log

https://gist.github.com/SquTM/f79c4776597d93f5d31886793eeb842b

**Comment by ZephyrWindSpirit** [comment]
old crash.
