### ISSUE TITLE
[Feature]: Add alternate end game content recipes for different play styles

### ISSUE THREAD

**Issue by TDY2012** [AllTheMods/Spellbound#44]
### Feature Details

The pack would serve more various play styles if we could "choose" suitable end game content recipes for ourselves. In my opinion, it is too tedious and repetitive just to gather materials for a single ATM star with 3 - 5 party members. However, it may effectively preserve a large scale server economic balance in a long run.

Here are some suggestions for all altered recipes, especially the ATM star:
1. Reduce its materials which require the same repetitive procedure to acquire. Forging one alloy in a dragon forge is no different from forging thousands in it.
2. These end game items should unlock something "new and rewarding" relative to the state which the player(s) are at. For instance, if the players could craft the ATM star with its current recipe, they would unlock a philosopher's stone. But at that point, they must have been achieved most things without it for so many times already.

**Comment by ZephyrWindSpirit** [comment]
Not planned at this time, but thank you for your input.
