### ISSUE TITLE
[Bug]: Can't hit Ice and Fire Dragons

### ISSUE THREAD

**Issue by CoolBeans427** [AllTheMods/Spellbound#45]
### Possible Fixes

Yes

### Modpack Version

other

### What happened?

Version 2.1.8. Can't hit Ice and Fire Dragons. It is not a damage issue or hitbox issue, I physically can't hit a dragon with bow or sword or magic. It gives that "poof" or "whiff" sound effect that indicates you can't hit the entity you're looking at. Similar to when you don't have permissions I guess. Playing on a multiplayer server that is running the modpack exactly how it came.

### latest.log

https://gist.github.com/CoolBeans427/91deb4235f8c93a4ee76f9c0c2b682f8

**Comment by Mitchell5200** [comment]
Optifine installed, Closing
