### ISSUE TITLE
[Bug]: Ars Nouveau flight is op

### ISSUE THREAD

**Issue by 1mphuls3** [AllTheMods/Spellbound#46]
### Feature Details

I'm not sure if this would be feature or bug, but ars nouveau flight is very op, its almost exactly the same as magic feather flight, but I can just make a create wood farm to fuel it.

 Basically its wood -> flight

I think the ritual tablet for flight should either be more expensive, or removed.

**Comment by ZephyrWindSpirit** [comment]
Thank you for the heads up, don't think its going to change. Ars ritual flight is location based, you have to be within its range before the timer runs out and the ritual requires source to run. Magic feather has no fuel, far as I know.
