### ISSUE TITLE
[Crash]: Crashed when activating Tablet of the Green Grove (Blood Magic)

### ISSUE THREAD

**Issue by Siegurd33** [AllTheMods/Spellbound#47]
### Possible Fixes

No

### Modpack Version

other

### What happened?

I had set up a small rotational Create farm and planted some mystical agriculture seeds in it. It was working just fine for an hour, but I got impatient and made a Blood Magic Sigil of the Green Grove. I went back to my farm and activated it, the game locked up immediately and then crashed. This was on version 2.1.8.

I tried reloading my game, but it now crashes when I try loading my world. Updated to 2.1.9, but issue persists. 

### Crash Log

https://gist.github.com/Siegurd33/91dda343fb5f8500917c04f1f1bf420c

**Comment by Siegurd33** [comment]
Loaded a backup from before the crash started, repeated the steps and still crash. 

Activating the sigil away from the farm works fine. Being anywhere near the create farm with the sigil causes the game to crash and become unloadable.

**Comment by ZephyrWindSpirit** [comment]
With updating blood magic to current, I do not receive this crash. Updating blood magic appears to solve it when around a single inferium plant.
