### ISSUE TITLE
[Bug]: zinc ingots can't change into nuggets

### ISSUE THREAD

**Issue by TheOne1201** [AllTheMods/Spellbound#48]
### Possible Fixes

Yes

### Modpack Version

2.1.4

### What happened?

zinc ingots can't change into nuggets

### latest.log

zinc ingots can't change into nuggets

**Comment by gxam** [comment]
FYI, this is still broken in 2.2.2.

**Comment by Himeki** [comment]
Still the case in 2.2.6

Zinc nuggets are used as another method of making andesite alloy (interchangeable with iron nuggets)

**Comment by ZephyrWindSpirit** [comment]
Fixed.
