### ISSUE TITLE
[Crash]: 2.1.9 Server does not start/crashes during startup

### ISSUE THREAD

**Issue by eeeeb** [AllTheMods/Spellbound#49]
### Possible Fixes

Yes

### Modpack Version

other

### What happened?

I tried to do a fresh setup of the 2.1.9 Server and it crashes/stops during startup. I tried that in a docker setup but also with just running the startserver.sh on an Ubuntu 20.04 server.

Each time I get the same error message (see attached gist)

### Crash Log

https://gist.github.com/eeeeb/e45d006e032936352e3a9a0f6fc2e392

**Comment by CRVSAD3R** [comment]
I also get this exact problem and I do not know how to fix it, I was really looking forward to making a server with this pack for me and my friends too.

**Comment by Mitchell5200** [comment]
Log link expired/deleted, Closing
