### ISSUE TITLE
No access to accessory(curio) solts

### ISSUE THREAD

**Issue by zwalk1017** [AllTheMods/Spellbound#50]
While playing I got a ring and when I do to equip it, nothing happens. Also, the icon/button is there to look at the accessory slots yet when I click on it, nothing opens to see all the slots. Am I missing something or is it a bug?

**Comment by gxam** [comment]
Is this still happening on version 2.2.2 of the pack?

Also, this pack has a lot of curio slots, you may have to scroll to see all of them.  The ring slots are near the bottom.

**Comment by Mitchell5200** [comment]
Confirmed fixed in V2.2.7, Closing
