### ISSUE TITLE
[Crash]: ATMS Client crash after server updating to latest version

### ISSUE THREAD

**Issue by ShadowMagnus000** [AllTheMods/Spellbound#51]
### Possible Fixes

Yes

### Modpack Version

other

### What happened?

After server updated to 2.1.10 everyone hard crashes after attempting to log in

### Crash Log

https://gist.github.com/ShadowMagnus000/d5fa0b11b28b0d4f8d3dec4d9925c70e

**Comment by ZephyrWindSpirit** [comment]
Old crash.
