### ISSUE TITLE
[Crash]: Unable to load world (SSP)

### ISSUE THREAD

**Issue by ClockwiseGear** [AllTheMods/Spellbound#52]
### Possible Fixes

Yes

### Modpack Version

other (2.1.11)

### What happened?

Crash happened after attempting to open inventory in base. Game hang for extended period, and as soon as I clicked the close button on the window, the game seemed to unfreeze for a moment before closing. The Minecraft launcher reappeared and indicated that the game had crashed, but no crash report was generated. 

I next attempted to relaunch the pack from the minecraft launcher, which is when the game displayed an error stating that Blue Skies had thrown an error while loading mods (see crash report). 

Closed the Minecraft launcher and re-opened. I was able to get to the main menu, but when I tried to load my world, the gamee seemed to hang on "Joining World" for an extended period of time

### Crash Log

https://gist.github.com/ClockwiseGear/0481dbd85f37e384c6a607b35d4d6c42

**Comment by ZephyrWindSpirit** [comment]
Optifine and rubidium crash on join.
But that's not your problem. Old crash.
