### ISSUE TITLE
[Bug]: OpenGL Error 1281 when using Framed Blocks

### ISSUE THREAD

**Issue by ThatCodeGuy821** [AllTheMods/Spellbound#53]
Was decorating my base when i saw the framed blocks and framed block slabs and thought that the would be a nice way of adding some cool effects to the base. but every few seconds the chat comes up with the OpenGL Error 1281 non stop. I have search for a solution but could not find any clear answers on how to fix the issue.

![Screenshot 2021-12-06 062641](https://user-images.githubusercontent.com/77604267/144854090-f657a797-f9a0-47c4-a904-d182a6aa4fc2.jpg)
s.

### latest.log

https://mclo.gs/6MrhVRr

**Comment by Pdiddy973** [comment]
that is a optifine issue, you can disable the error output in settings.
