### ISSUE TITLE
[Bug]: he Conversion Upgrade for Storage Drawers does not work.

### ISSUE THREAD

**Issue by Rawrling** [AllTheMods/Spellbound#56]
### Possible Fixes

Yes

### Modpack Version

other

### What happened?

Pack version 2.1.11

In the mod Storage Drawers one of the upgrades available is the Conversion Upgrade. The purpose of it is to take items that are the same item and allow them to be placed into the drawer. As an example to my confusing statement; More then one mod adds copper ore into the game. In function they are the exact same item but because they are from different mods they will not stack and are not treated as the same. With the upgrade in the drawer, items that are like that will stack into the drawer and convert into the first type put into the drawer. 

So the expected result would be that I put in copper ore from the mod "AllTheOres" and then I apply the Conversion Upgrade. Then any ore tagged to be the same item (forge:ores/copper) should then convert from their own mod version of copper ore to being "AllTheOres" copper when inserted into the drawer.

I am using the Astral Sorcery ritual of Mineralis to turn a large area of stone in the mining dim into random ore. Then using Blood magic rituals to auto mine the result. (ritual of magnetization and crushing). The Astral Sorcery ritual generates seemingly anything tagged as ore so i am getting ore from all mods in the pack as far as I can tell.

### latest.log

https://gist.github.com/Rawrling/3070a9b808bce04ddb2500a746d5b618

**Comment by ZephyrWindSpirit** [comment]
Old issue, Update and run a mineralis ritual, and get back to us on this.
