### ISSUE TITLE
[Crash]: Ghost mob in "THE OTHER" Dimension causes game to stop responding until forced to close

### ISSUE THREAD

**Issue by ThatCodeGuy821** [AllTheMods/Spellbound#57]
### Possible Fixes

Yes

### Modpack Version

other

### What happened?

Version 2.2.1

The thing is that the crash only effects client side not server side. My game crashes but the server will still think i am online even after I force the game to close. I receive no crash report afterwards either.

This has been happening for a while but i ignored it thinking i just would not go into the dimension but I really want to fight a dragon but i cannot do that if i can not enter the dimension in fear of crashing. I do not have Optifin installed I removed it.

### Crash Log

~~~

**Comment by Mitchell5200** [comment]
Unable to re-create on 2.2.7, closing
