### ISSUE TITLE
[Crash]: 

### ISSUE THREAD

**Issue by Drackion** [AllTheMods/Spellbound#59]
### Possible Fixes

Yes

### Modpack Version

other

### What happened?

Game crashes upon opening world

Pack: version 2.2.1

java.lang.IllegalArgumentException: 'other' is different type of Path

### Crash Log

https://gist.github.com/Drackion/18dc5510980bb7add850b6a20d6e8571

**Comment by Mitchell5200** [comment]
Optifine installed, Closing
