### ISSUE TITLE
[Bug]: vampirism guide nonfunctional, needs guide api vp

### ISSUE THREAD

**Issue by ZephyrWindSpirit** [AllTheMods/Spellbound#60]
### Possible Fixes

Yes

### Modpack Version

other

### What happened?

Another person mentioned vampirism book doesn’t work. We need to add guide api vp for it to function

### latest.log

Zip

**Comment by ZephyrWindSpirit** [comment]
https://github.com/AllTheMods/Spellbound/issues/58#issue-1077937266

**Comment by gxam** [comment]
This should be fixed in 2.2.2.
