### ISSUE TITLE
[Feature]: add goggles curio slot for create goggles

### ISSUE THREAD

**Issue by ZephyrWindSpirit** [AllTheMods/Spellbound#61]
### Feature Details

Other modpacks have a curios slot for create goggles. We should have that, and two bracelet slots. Two arms after all.

**Comment by ZephyrWindSpirit** [comment]
An easier way to do this is to add Create Plus which adds this for us. 
https://www.curseforge.com/minecraft/mc-mods/create-plus
Or, mess around with custom curios slots, which sounds difficult.

**Comment by Mitchell5200** [comment]
Confirmed fixed in V2.2.7, Closing
