### ISSUE TITLE
[Bug]: balancing: hostiles from mana and artifice and ars nouveau are too plentiful

### ISSUE THREAD

**Issue by ZephyrWindSpirit** [AllTheMods/Spellbound#62]
### Possible Fixes

Yes

### Modpack Version

other

### What happened?

I do have other mods installed, but the wilden mobs and factions mana and artifice mobs are very plentiful. Including druidcraft, I rarely see passive spawns in a dark forest. Beetles, wilden, m&a and the occasional vanilla mob. 

### latest.log

None

**Comment by SekhetBR** [comment]
The Abyss especially is absolutely crawling with mobs from these mods.

**Comment by MadWomen** [comment]
i'll have a look and see what i can do to fix it.
