### ISSUE TITLE
[Crash]: A given capability is null

### ISSUE THREAD

**Issue by warrook** [AllTheMods/Spellbound#63]
### Possible Fixes

Yes

### Modpack Version

other

### What happened?

pack version: 2.2.1 (current)

Was in combat against a vampire, game crashed. World crashes on load every time with the same error.

### Crash Log

https://gist.github.com/warrook/3e8a50cc0fd38f27556bb198a1bc8bcd

**Comment by ZephyrWindSpirit** [comment]
old crash. Update.
