### ISSUE TITLE
[Crash]: Ticking Player after equipping Living Armor

### ISSUE THREAD

**Issue by Timbroglio** [AllTheMods/Spellbound#64]
### Possible Fixes

Yes

### Modpack Version

other

### What happened?

Playing on 2.2.1, upon equipping all 4 pieces of the Blood Magic Living Armor set, immediately there's a Ticking Player error making it impossible to stay connected to the server.

### Crash Log

https://gist.github.com/Timiryazev/a173f61973d34392d5400d784536fc77

**Comment by MadWomen** [comment]
hopefully its fixed in the next version after the mod update stating this issue.

**Comment by Mitchell5200** [comment]
Blood Magic 1.16.4-3.1.7-27 claims to have fixed the issue, Confirmed fixed in V2.2.7, Closing
