### ISSUE TITLE
[Crash]: item in slot crashes game.

### ISSUE THREAD

**Issue by Floryder-Blackspire** [AllTheMods/Spellbound#68]
### Possible Fixes

Yes

### Modpack Version

other

### What happened?

while using latest version (2.2.1) i get a crash issue after traveling around, i can fix it temporarily by force killing myself and respawning. only issue is when i return to get my items the game crashes again.

### Crash Log

<script src="https://gist.github.com/Floryder-Blackspire/bd17eb1c8453058d5fcf46082f5d576b.js"></script>

**Comment by MadWomen** [comment]
that crashlog isn't loading correctly for me to take a look at.
