### ISSUE TITLE
[Question]: 

### ISSUE THREAD

**Issue by Viaton** [AllTheMods/Spellbound#69]
### What would you like to know?

Is this a bug or a feature? It seems too obvious to be unintentional. When trying to craft items with only one slot open in your inventory, and shift clicking will create more items than you can hold, the ingredients you are using will double. For example, I was crafting fir planks using a stack of logs with only one inventory slot open, and suddenly I had at least double the logs. It didn't even spill planks onto the ground. I did it a few more times, and ended up with 98k logs. Upon exiting the crafting table, all the logs dumped on the ground in a pile, causing immense lag. I didn't have cheats enabled, and I was only a few minutes in to the world.

**Comment by ZephyrWindSpirit** [comment]
Didnt' specify being a crafting table or a crafting station. Closed.
