### ISSUE TITLE
[Bug]: even with the right spellrod i simply can't make psimetal

### ISSUE THREAD

**Issue by gabrielminoru2022** [AllTheMods/Spellbound#70]
### Possible Fixes

Yes

### Modpack Version

other

### What happened?

i can make psidust but i simply can't make psi metal
![Captura de Tela (115)](https://user-images.githubusercontent.com/97371081/148666381-972ef2d1-df50-4d38-861f-64e04a823b59.png)

### latest.log

https://gist.github.com/

**Comment by gxam** [comment]
Did you create a spell with trick infusion?
