### ISSUE TITLE
[Bug]: Ars Nouveau Glyph of Slowfall shows as Tier 1 in the quest book.

### ISSUE THREAD

**Issue by SleepsAlot8143** [AllTheMods/Spellbound#76]
### Possible Fixes

No

### Modpack Version

other

### What happened?

Using mod version 2.1.11, Ars Nouveau's Glyph of Slowfall shows up as a Tier 1 glyph in the quest book when it is actually a Tier 2 glyph.

### latest.log

https://gist.github.com/SleepsAlot8143/ed9346b9eb3d9c687be177b35381b7c4

**Comment by gxam** [comment]
Also, Glyph of Delay is in with the T3 glyphs but is T1.

**Comment by gxam** [comment]
And these are missing:
* T1 Evaporate
* T1 Sensitive
* T1 Toss
* T1 Bounce
* T2 Sentient Harm
* T2 Wind Shear
* T3 Linger
* T3 Glide
* T3 Orbit

**Comment by ZephyrWindSpirit** [comment]
Added.
