### ISSUE TITLE
[Feature]: Default UI position changes

### ISSUE THREAD

**Issue by Zirnike** [AllTheMods/Spellbound#77]
### Feature Details

If the default Mahou position is 25 (X) instead of 10, it aligns with the (I believe) mana and artifice mana bar without overlapping the star at the beginning of the bar, as well as not crowding the nature's aura bar, making for a cleaner look.  Also, The One Probe defaults to top left, behind these there UI elements.  I cannot find the setting to adjust this by default (I had to use the one probe sheet GUI to do it).  I tried setting X=4750 (left edge 250 from center), but these seemed to have no effect on position.  Perhaps a config on the pack side could be set to default it to top center?

As an aside, the minimap (on every modpack, it seems) overlaps the UI element for potion (etc.) effects.  If there are more granular options to move it to the left somewhat, this would also improve usability and general UI 'niceness'.

**Comment by ZephyrWindSpirit** [comment]
Going to update the mahou setup to move over to 25 x and 24 y, and it looks better. Thanks for the feature idea. 
One probe is easily fixable by shift right-clicking the air with the one probe sheet of the akashic tome to make it mobile.
