### ISSUE TITLE
[Question]: 

### ISSUE THREAD

**Issue by ClockwiseGear** [AllTheMods/Spellbound#78]
### What would you like to know?

I was messing around my base and suddenly some really intense techno music started playing. I couldn't seem to find what was causing it, and after a while it went away. What's going on?

pack version 2.2.2
mods added: 
• Creeper Confetti
• Loot Beams
• Mighty Architect
• Minecolonies
• Pharmacist
• Second Chancee
• Tarot
• Traveler's Titles

**Comment by Cake12356** [comment]
It is likely a mob that spawned with a backpack with the Jukebox upgrade, and had the Gaia Guardian fight disc playing

**Comment by gxam** [comment]
It could be the abyss, try muting end_game_music:theabyss

**Comment by tunse80** [comment]
Hello, I was wondering the same thing. I have the game music turned off and then all of a sudden these two or three different, bass-heavy electronic tracks start playing. It's not some piano jukebox-thingy - it's global and keeps playing even when I move around. I haven't played Cyberpunk, but it sounds like it would fit into that game. Plus, it's really loud so I have to adjust the volume when it starts to play. It was fun at first, but now it's really annoying. I hope someone knows what this is and would let me know. I've searched a lot online and looked around in the config files but it's hard when you don't know what to look for :(

**Comment by ClockwiseGear** [comment]
It turns out that yes, mobs can spawn with Sophisticated Backpacks that
have a jukebox upgrade installed and with a music disk playing. The track
is from the Abyss mod.
