### ISSUE TITLE
Not being able to move enchants to books with grindstone

### ISSUE THREAD

**Issue by eseven77** [AllTheMods/Spellbound#79]
It looks like I am not able to move enchants to books with the grindstone. I am not sure if this is limited by another mod or if it's a bug.
I am on the latest version and paying from a Mac if that can helping

**Comment by InfiniteMalice** [comment]
I think it is disabled. Evilcraft you remove enchants with a blood crucible and b**l**ook.  Or you can do it with Coral Tombstone and disenchant book.

**Comment by ZephyrWindSpirit** [comment]
Hi, fellow mac player here.
The minecraft grindstone has never had that sort of functionality to my knowledge. It strips enchantments and gives back a smidge of xp. 
Infinite malice is right, use blooks with evilcraft or corail tombstone and the tome of disenchantment. 
This isn't a bug, to my knowledge.
