### ISSUE TITLE
[Bug]: Mahou Tsukai no bleeding effect

### ISSUE THREAD

**Issue by Githubwontletmeusemyname** [AllTheMods/Spellbound#80]
### Possible Fixes

Yes

### Modpack Version

other

### What happened?

I can't use Mahou Tsukai, because I don't get the bleeding effect, which means i cannot draw the circle to get started. I tried reinstalling the mod, different keybinds, turning into human again but nothing seems to work.

### latest.log

https://gist.github.com/Githubwontletmeusemyname/7638da5f2cc384072c1f879bd4059eec#file-latest-log

**Comment by gxam** [comment]
If you updated your world from 2.2.1, you may be running in the potion id issue #75

**Comment by Githubwontletmeusemyname** [comment]
> If you updated your world from 2.2.1, you may be running in the potion id issue #75

Yeah I heard about this issue after I posted this. I installed this potion id mod and it worked! 
Thank you very much

**Comment by Mitchell5200** [comment]
Potion ID fixer added to modpack, Confirmed fixed in V2.2.7, Closing
