### ISSUE TITLE
[Question]:  Shouldn't mundane armor be a part of allthemodium armor recipe?

### ISSUE THREAD

**Issue by MisterLious** [AllTheMods/Spellbound#81]
### What would you like to know?

Version 2.2.2

Allthemodium armor is currently very easy to get, as you can mine the ore just after crafting a basic Ars Nouveau spell book and using Touch → Break → 2x Amplify spell (doesn't even use an entire mana bar). Making it possible to get the whole set even before getting to nether. And if you get to nether and summon Marid Ore Crusher from Occultism, you only need 4 ores for the entire set (or just a bunch of gold and trade with piglins).

Solution

As at the moment mundane armor is not used at all, it'd be a natural step to change allthemodium armor recipe to use mundane armor. Currently, t's the only recipe from that mod that doesn't need more advanced items like Allthemodium alloys.

**Comment by ZephyrWindSpirit** [comment]
Its a choice if you aren't upgrading, far as I know.
