### ISSUE TITLE
"Spice of Life: Carrot Edition" improve configs

### ISSUE THREAD

**Issue by superkitten12** [AllTheMods/Spellbound#82]
### Feature Details

Currently, spice of life (the mod that gives hearts for eating unique foods) seems to be running on the default configs(new hearts every 5 foods, capping at 25 food), despite having Famer's Delight and a few other food adding mods, giving the player 433 total unique foods. This is an issue because you can pretty much get all ten hearts from the mod just from eating raw ingredients, and doesn't encourage actually going out of your way whatsoever to engage with creating food, such as the mod intends. My suggestion is to either space out the current milestones and/or and new ones in order to utilize at least 250-350 of the foods to get max health. I already edited my configs to include new milestones at 50, 100, 200, and 400 foods just so i can get dopamine for making food, but i know not everyone is comfortable with editing the configs of packs themselves(like they are cheating or not playing as intended). Thank you for your consideration.

**Comment by ZephyrWindSpirit** [comment]
Added up to 500 unique foods in config.
