### ISSUE TITLE
[Question]: Nausea after finishing Sanctum Mana and Artifice

### ISSUE THREAD

**Issue by BadImmortal** [AllTheMods/Spellbound#83]
### What would you like to know?

I havent touched any other mods really apart from Ars Novea, but since finishing the sanctum from mana and artifice, I have nausea whenever in the area of it, is there a solution?

**Comment by BadImmortal** [comment]
Version 2.2.2.2

**Comment by gxam** [comment]
This may be the potion id issue #75  I know that sanctum gives you a potion effect.

**Comment by Mitchell5200** [comment]
Potion ID fixer added to modpack, Confirmed fixed in V2.2.7, Closing
