### ISSUE TITLE
[Bug]: End city and ship chests not converting to Lootr chests

### ISSUE THREAD

**Issue by Timelife** [AllTheMods/Spellbound#84]
### Possible Fixes

Yes

### Modpack Version

other

### What happened?

As the title mentions, chest in End cities and ships are not being converted to Lootr chests.

### latest.log

https://gist.github.com/Timelife/84d886437334da629c700ba69ff81222

**Comment by Mitchell5200** [comment]
Confirmed fixed in V2.2.7, Closing
