### ISSUE TITLE
[Bug]: Can't tame Alpine dragons 

### ISSUE THREAD

**Issue by Vindication10** [AllTheMods/Spellbound#88]
Not able to tame the alpine dragons. Mods on the Reddit Wyrmroost seem to think that the resource bees mod might be the problem since it changes the vanilla bees.

**Comment by ZephyrWindSpirit** [comment]
Did you make sure its a pollinated vanilla bee? I just watched someone playing spellbound on youtube tame four alpine dragons in a row. You may be unlucky, try again?

**Comment by ZephyrWindSpirit** [comment]
Closing to inactivity, will test
