### ISSUE TITLE
[Crash]: 

### ISSUE THREAD

**Issue by ShieldManH** [AllTheMods/Spellbound#92]
### Possible Fixes

Yes

### Modpack Version

other

### What happened?

I'm on the version Sepllbound 2.2.3 

I had a 9x9 farm field with 63 supremium accelerators underneath almost every block and a create mod spinning harvester when I planted tea from farmers delight mod it crashed on me and never opened my world again and every time I open it it says :

![Crash](https://user-images.githubusercontent.com/76407731/152182126-0030a376-3d36-44e5-87ee-f70e6a8ea4c6.jpg)

[crash-2022-02-02_17.59.12-server.txt](https://github.com/AllTheMods/Spellbound/files/7987664/crash-2022-02-02_17.59.12-server.txt)

Thank you,
ShieldManH

### Crash Log

https://gist.github.com/ShieldManH/c16e7dcf244df4d93d5f8e3b6adc4fc8

**Comment by MadWomen** [comment]
ive decided to remove that mod all together with the many bugs it has, so that should fix your issue next update.

**Comment by ShieldManH** [comment]
I forgot to come back with an update on the situation, but after submitting this report I went and downloaded Amulet world editor and it worked flawlessly after voiding that block area. Was so happy that I forgot to come back and update the report.
Nevertheless, thanks for the response <3
