### ISSUE TITLE
[Crash]: Gamecrash on a server when a Witch hunter is nearby on a 2.2.4 server

### ISSUE THREAD

**Issue by Icaruslevelone** [AllTheMods/Spellbound#93]
### Possible Fixes

Yes

### Modpack Version

other

### What happened?

It happened a few times since the update now that whenever a Witchhunter is nearby my Game crashes
at least i think its because of the Witchhunter - i dont really know a lot about how to read a crash report
I also reinstalled the the mod pack but the same crash issue happened again

### Crash Log

https://gist.github.com/Icaruslevelone/3d8a1295adc4f07d7f21d2d55f8a749a

**Comment by SuppremeBlue** [comment]
I've been seeing that as well. Killing all nearby entities within a couple seconds of entering the game seems to resolve the issue until another one spawns.

**Comment by Schweigsam83** [comment]
It's happening to me too. Mana and Artifice and its depending mod GeckoLib got updates that diverge in their fixes for bugs and created so a new one.. i think they are already aware and working on it.
