### ISSUE TITLE
[Crash]: Single player world not loading up.

### ISSUE THREAD

**Issue by noob12334** [AllTheMods/Spellbound#94]
### Possible Fixes

Yes

### Modpack Version

other

### What happened?

My single-player world is loading up to the point of 100% and then shutting down immediately. 

### Crash Log

https://gist.github.com/noob12334/1bff27a85aaf47d50ccb8d01bc0b1b4e

**Comment by ZephyrWindSpirit** [comment]
Old crash. update.
