### ISSUE TITLE
[Crash]: game crashing few minuts after loading

### ISSUE THREAD

**Issue by thomasLecler** [AllTheMods/Spellbound#95]
### Possible Fixes

Yes

### Modpack Version

2.1.4

### What happened?

I was playing in my base near my chests and it crashed as I was walking. When I launched the game again, I spawn back at the same place can play few minutes and it chashed again.
The world was a solo one, created few months ago in an older version, the updated yesteday at 2.2.4.

### Crash Log

https://gist.github.com/thomasLecler/7d9d5a0d486291c9ea151c4607267e92

**Comment by ZephyrWindSpirit** [comment]
WItch hunter crash. fixed.
