### ISSUE TITLE
[Bug]: Ring of the sky not craftable

### ISSUE THREAD

**Issue by Dubbywubwub** [AllTheMods/Spellbound#96]
### Possible Fixes

Yes

### Modpack Version

other

### What happened?

Playing on 2.2.5 . Tried to craft the Ring of the Sky for the Angel Ring, however when i use the recipe in JEI the item does not craft.
![2022-02-08 (3)](https://user-images.githubusercontent.com/99295719/153127644-5949bd31-a905-4b6e-9d03-e5d74f05e90f.png)
![2022-02-08 (2)](https://user-images.githubusercontent.com/99295719/153127648-eff0748b-c3b6-47d8-80b1-ce17dd8ed0c5.png)
.

### latest.log

https://gist.github.com/Dubbywubwub/6e914ac71dece5650ac31797d5477298

**Comment by Mitchell5200** [comment]
Confirmed working in V2.2.7, Closing
