### ISSUE TITLE
[Bug]: Eldrin crafting doesn't work

### ISSUE THREAD

**Issue by shBLOCK** [AllTheMods/Spellbound#97]
### Possible Fixes

Yes

### Modpack Version

2.2.5

### What happened?

When right clicking the eldrin alter to start the craft, nothing happends, and an error message is generated in the log.
(I only posted the error message part of the log)

### latest.log

https://gist.github.com/shBLOCK/43c2f8513b2dc25c2d77cb01e8ce687c

**Comment by ZephyrWindSpirit** [comment]
Update.
