### ISSUE TITLE
[Issue]: Performance is abysmally low

### ISSUE THREAD

**Issue by twothe** [AllTheMods/Spellbound#98]
### Feature Details

I just gave the latest version a try, however I sadly had to notice that the performance of this pack is extremely low. Aside from the world generation hiccups, my fps is about 20-30 constantly. In comparison when playing ATM 6 or ATM 7 I usually have 70-100 fps.

I used [sparc](https://spark.lucko.me/zXE9WkNcDN) to try to pinpoint a specific source, but there doesn't seem to be anything in particular that causes the low fps, it seems that the pack in general is just extremely slow, down to a point where it is unplayable. The only odd thing is that the sprite atlas is pretty busy swapping textures, no idea why though.

Please do some performance testing. No matter how good the pack is, if no one can play it then no one will play it.

**Comment by InfiniteMalice** [comment]
If you are using Cursed Forge, you can increase the memory used. My default was very low, and I increased it to 24 GB, and it now runs smoothly. Click on the game without clicking on play. You should now see three-dot options; click on that. Profile Options should allow you to increase the memory used.
