### ISSUE TITLE
[Question]: quest popup not dissapearing

### ISSUE THREAD

**Issue by RustyCarKeys** [AllTheMods/Spellbound#99]
### What would you like to know?

I have a popup for the collect 16 dark gem quest for EvilCraft on the right side of my screen, and I have no idea how to get rid of it. Ive tried rejoining, and restarting the game. How do I get rid of this pop up
![Screenshot (309)](https://user-images.githubusercontent.com/86811610/154362762-d0888ce3-2c6a-44cb-9af5-8ebdbddfc77d.png)
?

**Comment by Mitchell5200** [comment]
Quest pinned in Questbook

Closing
